### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by DRIFTKINGEVO** [TasoOneAsia/t-notify#1]
using bottom-center gets the notifications on the actual CENTER of the screen, is there any way to get them right on the bottom of the screen?

**Comment by TasoOneAsia** [comment]
There is a way of doing that, in-fact, by using custom CSS styling to overwrite the defaults. 
You can learn a little about how to do that [here.](https://docs.tasoagc.dev/#/usage?id=custom-classes-guide)

If you are looking for further support, my [Discord](https://discord.gg/ewvbgb5) is a good place to go to get scripting support. Also, I may consider making it easier in the future to use Lua to style but **no** promises.
