### ISSUE TITLE
Gradient on a custom not working?

### ISSUE THREAD

**Issue by nrcsantos** [TasoOneAsia/t-notify#11]
I have tried to use the 'Custom' features but for some reason the background always shows 'transparent':

My custom.css:

```
.gn-example2 {	
	background: rgb(169,195,110);
	background: radial-gradient(circle, rgba(169,195,110,1) 0%, rgba(112,141,175,0) 100%);
	color: white;
}
```

My export (client side):

```
exports['t-notify']:Custom({
		style = 'gn-example',
		title = 'Pagamentos',	
		sound = true,
		message = 'Recebeste guito \n teste dois',
		duration = 4500,
		custom = true
		})
```

**Comment by BombayV** [comment]
@nrcsantos is this client side or server side? + You have to use style = 'example2'

**Comment by TasoOneAsia** [comment]
The gn part is prepended automatically as @XiosBombay said. You need to use
```
style = example2
```
instead of what you currently have.

**Comment by TasoOneAsia** [comment]
As there hasn't been any updated information with this issue it is being closed.
