### ISSUE TITLE
Enhancement: Getter for if a notification is active

### ISSUE THREAD

**Issue by RockySouthpaw** [TasoOneAsia/t-notify#20]
### Suggestion 1
- Getter for if a persistent notification is active or not with a specified ID. 
  - Currently you just clear it just in case its active which results in:
![image](https://user-images.githubusercontent.com/55056068/149461042-f128669a-c004-49fd-af15-0cfb482162a5.png). This would resolve this use case.

### Suggestion 2
- Clear or hide all notifications.
  - In the event you're entering a photo mode and you don't want any, this would ether clear them all or hide them. Helpful if you're using a resource that isn't the one creating them and you wanna cover edge cases of where you want none on the screen.

**Comment by BombayV** [comment]
Added in #21
