### ISSUE TITLE
[Enhancement] - Notification History

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [TasoOneAsia/t-notify#22]
Do we have an ETA on when this feature will be added? We use t-notify for our 911 call system. It would be incredible if we could look back at some of the notifications. Thanks!

**Comment by BombayV** [comment]
This will be done once #23 gets merged into master.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> This will be done once #23 gets merged into master.

Looking forward to notification history
