### ISSUE TITLE
[Bug Report] - MIME Type Issue

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [TasoOneAsia/t-notify#26]
`[    110453] [b2802_GTAProce]        CrBrowserMain/ Refused to apply style from 'https://cdn.jsdelivr.net/gh/hung1001/font-awesome-pro-v6@44659d9/css/all.min.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled. (@t-notify/nui/main.html:0)`

Would anybody know how to update this or whatever?

**Comment by BombayV** [comment]
This should be fixed in the latest commit on history.
