### ISSUE TITLE
[Bug Report] - Error in first notification

### ISSUE THREAD

**Issue by Richards0nd** [TasoOneAsia/t-notify#6]
**Release Version**
v1.30
**Describe the bug**
Hello ... I found a problem in the script.

Whenever I restart the server, and people enter the server, when they receive the first notification of the script, it ends up buggy and does not leave the screen.
The other notifications disappear normally.

The code I'm using for all notifications is this:
```
TriggerClientEvent('t-notify:client:Alert', _source, {
			style = 'success',
			message = '✔️ Você depositou R$'..amount,
			duration = 2000,
			position = 'bottom-center',
			sound = true
		})
```

I always have to restart the script, for it to work normally ...
This gets a little boring, because whenever the server restarts, I have to restart the script. I've tried to put it to start at the end, I've tried to put it to restart itself at the end ... but it didn't work, you have to wait for someone to enter the server, and then you have to restart.

EDIT:
Actually, it's not just the first notification ...
He's bugged even in the following ...

Only after restarting the script does it work 100%
https://i.imgur.com/fgPDz9r.png
There is no error in the console, and neither in DEBUG.

**Expected behavior**
The first notification was supposed to work normally.

**Comment by TasoOneAsia** [comment]
Hi there,

Can you confirm that T-Notify is being loaded before any dependencies, because this sounds like a dependency related issue possibly.

**Comment by Richards0nd** [comment]
Yes, it's being loaded later ...
But I've tried to put it before ... and the problem continues.

**Comment by BombayV** [comment]
This should have been fixed in the latest updates.

**Comment by TasoOneAsia** [comment]
As there hasn't been any recent updates about this issue, it is being closed.
