### ISSUE TITLE
[Bug Report] - 

### ISSUE THREAD

**Issue by PaulRobson2002** [TasoOneAsia/t-notify#7]
**Release Version**

**Describe the bug**

**To Reproduce**
Download and start the resource

**Expected behavior**
https://gyazo.com/955992d60baf962700a23ad75fc02783

**Comment by BombayV** [comment]
@PaulRobson2002 Did you download t-notify from the release tab?
https://github.com/TasoOneAsia/t-notify/releases/tag/v1.3.1

**Comment by PaulRobson2002** [comment]
Yes

**Comment by BombayV** [comment]
Do you mind showing me a picture of the actual folder? Like what's inside of it

**Comment by PaulRobson2002** [comment]
I re downloaded it and it works now so 🤷‍♂️
